version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT:-5000}
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:${BACKEND_PORT:-5000}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongodb_data: